# Generated by Django 2.1.7 on 2019-02-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Task',
        ),
    ]
