# Generated by Django 2.1.7 on 2019-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0002_auto_20190216_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'creada'), ('revised', 'revisada'), ('marked', 'marcada'), ('deleted', 'deleted')], default='created', max_length=32),
        ),
    ]
